/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* This code was generated by avrogencpp 1.12.0-SNAPSHOT. Do not edit.*/

#ifndef WORKER_POLICIES_AVRO_OBJECT_HH_2852311604_H
#define WORKER_POLICIES_AVRO_OBJECT_HH_2852311604_H


#include <sstream>
#include <any>
#include "build/_deps/avro-src/lang/c++/api/Specific.hh"
#include "build/_deps/avro-src/lang/c++/api/Encoder.hh"
#include "build/_deps/avro-src/lang/c++/api/Decoder.hh"

namespace avro_serialization {
struct Object {
    std::string str;
    std::vector<int64_t > array;
    std::map<std::string, int64_t > map;
    int64_t number;
    double floating_number;
    bool boolean;
    Object() :
        str(std::string()),
        array(std::vector<int64_t >()),
        map(std::map<std::string, int64_t >()),
        number(int64_t()),
        floating_number(double()),
        boolean(bool())
        { }
};

}
namespace avro {
template<> struct codec_traits<avro_serialization::Object> {
    static void encode(Encoder& e, const avro_serialization::Object& v) {
        avro::encode(e, v.str);
        avro::encode(e, v.array);
        avro::encode(e, v.map);
        avro::encode(e, v.number);
        avro::encode(e, v.floating_number);
        avro::encode(e, v.boolean);
    }
    static void decode(Decoder& d, avro_serialization::Object& v) {
        if (avro::ResolvingDecoder *rd =
            dynamic_cast<avro::ResolvingDecoder *>(&d)) {
            const std::vector<size_t> fo = rd->fieldOrder();
            for (std::vector<size_t>::const_iterator it = fo.begin();
                it != fo.end(); ++it) {
                switch (*it) {
                case 0:
                    avro::decode(d, v.str);
                    break;
                case 1:
                    avro::decode(d, v.array);
                    break;
                case 2:
                    avro::decode(d, v.map);
                    break;
                case 3:
                    avro::decode(d, v.number);
                    break;
                case 4:
                    avro::decode(d, v.floating_number);
                    break;
                case 5:
                    avro::decode(d, v.boolean);
                    break;
                default:
                    break;
                }
            }
        } else {
            avro::decode(d, v.str);
            avro::decode(d, v.array);
            avro::decode(d, v.map);
            avro::decode(d, v.number);
            avro::decode(d, v.floating_number);
            avro::decode(d, v.boolean);
        }
    }
};

}
#endif
